Задание 1
maladetska/go-microservices-course pull request #2
Opened 2024-03-28 00:03 UTC by maladetska

2024-03-29 15:45 UTC, kirreal commented
Проверял на строке:
Isn't she lovely? By the way I believe she's got it and I'd like being around.

результат:
lovely? way believ got like aroud.

2024-03-29 15:59 UTC, kirreal requested changes

2024-03-29 15:59 UTC, kirreal commented on stemming/myapp/Makefile
> +	go build -o ${BINARY_NAME} main.go needless_words_dictionary.go stemmer.go
go build не должен содержать перечисление всех файлов

2024-03-29 15:59 UTC, kirreal commented on stemming/myapp/go.sum
> +github.com/BurntSushi/toml v1.3.2/go.mod h1:CxXYINrC8qIiEnFrOxCa7Jy5BFHlXnUU2pbicEuybxQ=
Чтобы почистить историю можно выполнить go mod tidy

2024-03-29 15:59 UTC, kirreal commented on stemming/myapp/main.go
> +	textPtr := flag.String("s", "different words", "words for stemming")
Тут проще использовать flag.StringVar(&text, ...) в таком случае не придется разименовывать указатель дальше

2024-03-29 15:59 UTC, kirreal commented on stemming/myapp/main.go
> +	var words = strings.Fields(*textPtr)
Тут лучше попробовать использовать strings.FieldsFunc

2024-03-29 15:59 UTC, kirreal commented on stemming/myapp/stemmer.go
> +func isWordWithApostropheOk(str string) bool {
Не обязательно добавлять суффикс Ok к названию функции isWordWithApostrophe

2024-03-29 15:59 UTC, kirreal commented on stemming/myapp/stemmer.go
> +	for i := 0; i < len(words); i++ {
Тут можно использовать цикл с range for _, w :=  range words {}

2024-03-29 15:59 UTC, kirreal commented on stemming/myapp/main.go
> +func PrintResult(set []interface{}) {
Неплохая идея с set'ом, хотя и немного усложняет решение задачи. 
В нашем конкретном случае - это не важно, но порядок входящей строки меняется. И такое ощущение, что тут подошел бы map[string]interface{}, но это не ошибка конечно

2024-03-30 02:01 UTC, maladetska commented on stemming/myapp/stemmer.go
> +func isWordWithApostropheOk(str string) bool {
Не совсем: не все слова с апострофом стоит исключать. Пример:
o'clock, O'neill -- в данном случае слова с апострофом, но они OK
it's, I'm, I'll -- не OK

2024-03-30 02:13 UTC, maladetska commented on stemming/myapp/main.go
> +func PrintResult(set []interface{}) {
Да, но во втором пункте "Критерии приемки" сказано, что программа "выводит на экран
слова <...> **в любом порядке**", поэтому стоит ли обращать внимание порядок?

2024-03-30 02:18 UTC, maladetska commented on stemming/myapp/Makefile
> +	go build -o ${BINARY_NAME} main.go needless_words_dictionary.go stemmer.go
fixed

2024-03-30 02:18 UTC, maladetska commented on stemming/myapp/main.go
> +	textPtr := flag.String("s", "different words", "words for stemming")
fixed

2024-03-30 02:19 UTC, maladetska commented on stemming/myapp/main.go
> +	var words = strings.Fields(*textPtr)
fixed

2024-03-30 02:19 UTC, maladetska commented on stemming/myapp/stemmer.go
> +	for i := 0; i < len(words); i++ {
fixed

2024-03-30 22:38 UTC, maladetska commented on stemming/myapp/stemmer.go
> +func isWordWithApostropheOk(str string) bool {
fixed

2024-04-01 07:57 UTC, vbelogrudov approved these changes
все очень неплохо!

2024-04-01 07:57 UTC, vbelogrudov commented on stemming/myapp/stemmer.go
> +func stemming(words []string) *hashset.Set {
в идеале, конечно, возвращать  слайс слов. Клиент ничего не хочет знать о  *hashset.Set :)

2024-04-01 07:57 UTC, vbelogrudov commented on stemming/myapp/stemmer.go
> +	var stemmedWords = hashset.New()
map[string]bool был бы идеальным эмулятором сета

2024-04-01 07:57 UTC, vbelogrudov commented on stemming/myapp/stemmer.go
> +	if wordsAfterApostrophe.Contains(words[1]) {
можно сократить до одной строчки весь if/else

2024-04-01 09:26 UTC, maladetska commented on stemming/myapp/stemmer.go
> +func stemming(words []string) *hashset.Set {
Да, действительно, вы правы

2024-04-01 09:26 UTC, maladetska commented on stemming/myapp/stemmer.go
> +func stemming(words []string) *hashset.Set {
fixed

2024-04-01 09:26 UTC, maladetska commented on stemming/myapp/stemmer.go
> +	var stemmedWords = hashset.New()
fixed

2024-04-01 09:26 UTC, maladetska commented on stemming/myapp/stemmer.go
> +	if wordsAfterApostrophe.Contains(words[1]) {
fixed

2024-04-01 09:28 UTC, merged